callback_main_menu = "main_menu"
callback_server_status = "server_status"
callback_player_count = "player_count"
callback_check_my_role = "check_my_role"
callback_get_permission = "get_permission"
callback_admin_action = "admin_action"
callback_start_server = "start_server"
callback_none = "none"
callback_user_settings = "user_settings"
callback_file_settings = "file_settings"
callback_ssh_settings = "ssh_settings"
callback_select_players = "select_players"
callback_settings_role = "settings_role:"
callback_list_file = "list_file" #TODO
callback_delete_local_files = "delete_local_files" #TODO
callback_list_remote_files = "list_remote_files" #TODO
callback_delete_remote_files = "delete_remote_files" #TODO
callback_stop_server = "stop_server" #TODO - точно нужно
callback_accept_moderator = "confirm:"
callback_reject_moderator = "cancel:"
callback_delete_user = "delete:"